package com.travel.wifimap.domain;


//@DynamoDBTable(tableName = "T_CHECKIN")
public class Checkin extends BaseEntity {

	private String id;
	private String userId;
	private String venueId;
	private String commentId;

	private Checkin() {
		super();
	}

	// @DynamoDBHashKey(attributeName = "ID")
	// @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	// @DynamoDBAttribute(attributeName = "USER_ID")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	// @DynamoDBAttribute(attributeName = "VENUE_ID")
	public String getVenueId() {
		return venueId;
	}

	public void setVenueId(String venueId) {
		this.venueId = venueId;
	}

	// @DynamoDBAttribute(attributeName = "COMMENT_ID")
	public String getCommentId() {
		return commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

}
