package com.travel.wifimap.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "T_FEEDBACK")
// @DynamoDBTable(tableName = "T_FEEDBACK")
public class Feedback extends BaseEntity {

	private String id;
	private String fromName;
	private String fromEmail;
	private String body;
	private String lang;

	public Feedback() {
		super();
	}

	@Id
	@Column(name = "ID")
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	// @DynamoDBHashKey(attributeName = "ID")
	// @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "FROM_NAME")
	// @DynamoDBAttribute(attributeName = "FROM_NAME")
	public String getFromName() {
		return fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Column(name = "FROM_EMAIL")
	// @DynamoDBAttribute(attributeName = "FROM_EMAIL")
	public String getFromEmail() {
		return fromEmail;
	}

	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}

	@Column(name = "BODY")
	// @DynamoDBAttribute(attributeName = "BODY")
	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "LANG")
	// @DynamoDBAttribute(attributeName = "LANG")
	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Feedback[from:").append(fromName).append(", ")
				.append(fromEmail).append("] lang:").append(lang)
				.append(" text:").append(body);
		return sb.toString();
	}
}
