package com.travel.wifimap.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "T_USER")
// @DynamoDBTable(tableName = "T_USER")
public class User extends BaseEntity {

	private String id;
	private String name;
	private String password;
	private String firstName;
	private String lastName;
	private String country;
	private String state;
	private String city;
	private String email;
	private String phone;
	private Date birthDate;
	private String gender;

	// @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade =
	// CascadeType.ALL)
	// private List<SocialProfile> links;

	// @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade =
	// CascadeType.ALL)
	// private List<Device> devices;

	public User() {
		super();
	}

	@Id
	@Column(name = "ID")
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	// @DynamoDBHashKey(attributeName = "ID")
	// @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME")
	// @DynamoDBAttribute(attributeName = "NAME")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FIRST_NAME")
	// @DynamoDBAttribute(attributeName = "FIRST_NAME")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME")
	// @DynamoDBAttribute(attributeName = "LAST_NAME")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL")
	// @DynamoDBAttribute(attributeName = "EMAIL")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE")
	// @DynamoDBAttribute(attributeName = "PHONE")
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "BIRTH_DATE")
	// @DynamoDBAttribute(attributeName = "BIRTH_DATE")
	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "GENDER")
	// @DynamoDBAttribute(attributeName = "GENDER")
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "CITY")
	// @DynamoDBAttribute(attributeName = "CITY")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY")
	// @DynamoDBAttribute(attributeName = "COUNTRY")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	// public List<SocialProfile> getLinks() {
	// return links;
	// }
	//
	// public void setLinks(List<SocialProfile> links) {
	// this.links = links;
	// }

	@Column(name = "STATE")
	// @DynamoDBAttribute(attributeName = "STATE")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "PASSWORD")
	// @DynamoDBAttribute(attributeName = "PASSWORD")
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
